name: wamra
description: "Water Meter Reading App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.0.7
  google_ml_kit: ^0.19.0
  image : ^3.0.1
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
